"""
Multi-agent orchestration system using LangGraph for SDLC workflow automation.

Each agent is responsible for a specific phase of the SDLC:
- Requirements Agent: Generates PRD, SRS, user stories, acceptance criteria
- Architecture Agent: Creates system architecture, ER diagrams, API contracts
- Database Agent: Designs database schemas, migrations, seed data
- Frontend Agent: Generates React/Next.js components and pages
- Backend Agent: Creates API endpoints, services, business logic
- Testing Agent: Generates unit, integration, and E2E tests
- CI/CD Agent: Creates Dockerfiles, GitHub Actions pipelines
- Deployment Agent: Manages deployment configurations
- Monitoring Agent: Sets up logging, metrics, alerting
"""

from dataclasses import dataclass, field
from enum import Enum
from typing import Any


class AgentType(str, Enum):
    REQUIREMENTS = "requirements"
    ARCHITECTURE = "architecture"
    DATABASE = "database"
    FRONTEND = "frontend"
    BACKEND = "backend"
    TESTING = "testing"
    CICD = "cicd"
    DEPLOYMENT = "deployment"
    MONITORING = "monitoring"


class SDLCPhase(str, Enum):
    IDEA = "idea"
    REQUIREMENTS = "requirements"
    ARCHITECTURE = "architecture"
    DEVELOPMENT = "development"
    TESTING = "testing"
    DEPLOYMENT = "deployment"
    MONITORING = "monitoring"


@dataclass
class AgentMessage:
    agent_type: AgentType
    content: str
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass
class SDLCState:
    """Shared state across all agents in the SDLC pipeline."""

    project_id: str
    prompt: str
    current_phase: SDLCPhase = SDLCPhase.IDEA
    tech_stack: dict[str, str] = field(default_factory=dict)

    # Artifacts generated by each agent
    prd: str = ""
    srs: str = ""
    user_stories: list[str] = field(default_factory=list)
    acceptance_criteria: list[str] = field(default_factory=list)
    architecture_doc: str = ""
    er_diagram: str = ""
    api_spec: str = ""
    db_schema: str = ""
    frontend_code: dict[str, str] = field(default_factory=dict)
    backend_code: dict[str, str] = field(default_factory=dict)
    test_suites: dict[str, str] = field(default_factory=dict)
    cicd_config: dict[str, str] = field(default_factory=dict)
    deployment_config: dict[str, str] = field(default_factory=dict)

    # Agent communication
    messages: list[AgentMessage] = field(default_factory=list)
    errors: list[str] = field(default_factory=list)


class BaseAgent:
    """Base class for all SDLC agents."""

    agent_type: AgentType

    def __init__(self, agent_type: AgentType) -> None:
        self.agent_type = agent_type

    async def execute(self, state: SDLCState) -> SDLCState:
        raise NotImplementedError

    def _add_message(self, state: SDLCState, content: str) -> None:
        state.messages.append(AgentMessage(agent_type=self.agent_type, content=content))


class RequirementsAgent(BaseAgent):
    def __init__(self) -> None:
        super().__init__(AgentType.REQUIREMENTS)

    async def execute(self, state: SDLCState) -> SDLCState:
        state.current_phase = SDLCPhase.REQUIREMENTS
        self._add_message(state, f"Analyzing prompt: {state.prompt[:100]}...")
        self._add_message(state, "Generating PRD, SRS, and user stories...")
        state.prd = f"# PRD for {state.prompt[:50]}\n\nGenerated requirements..."
        state.srs = f"# SRS for {state.prompt[:50]}\n\nTechnical specifications..."
        return state


class ArchitectureAgent(BaseAgent):
    def __init__(self) -> None:
        super().__init__(AgentType.ARCHITECTURE)

    async def execute(self, state: SDLCState) -> SDLCState:
        state.current_phase = SDLCPhase.ARCHITECTURE
        self._add_message(state, "Designing system architecture...")
        self._add_message(state, "Creating ER diagram and API contracts...")
        state.architecture_doc = "# System Architecture\n\nMicroservices architecture..."
        state.er_diagram = "# ER Diagram\n\nEntity relationships..."
        state.api_spec = "# API Specification\n\nRESTful endpoints..."
        return state


class DatabaseAgent(BaseAgent):
    def __init__(self) -> None:
        super().__init__(AgentType.DATABASE)

    async def execute(self, state: SDLCState) -> SDLCState:
        self._add_message(state, "Creating database schema and migrations...")
        state.db_schema = "-- Database Schema\nCREATE TABLE..."
        return state


class FrontendAgent(BaseAgent):
    def __init__(self) -> None:
        super().__init__(AgentType.FRONTEND)

    async def execute(self, state: SDLCState) -> SDLCState:
        state.current_phase = SDLCPhase.DEVELOPMENT
        self._add_message(state, f"Generating {state.tech_stack.get('frontend', 'React')} code...")
        state.frontend_code = {"App.tsx": "// Generated frontend code", "index.tsx": "// Entry point"}
        return state


class BackendAgent(BaseAgent):
    def __init__(self) -> None:
        super().__init__(AgentType.BACKEND)

    async def execute(self, state: SDLCState) -> SDLCState:
        self._add_message(state, f"Generating {state.tech_stack.get('backend', 'FastAPI')} code...")
        state.backend_code = {"main.py": "# Generated backend code", "models.py": "# Database models"}
        return state


class TestingAgent(BaseAgent):
    def __init__(self) -> None:
        super().__init__(AgentType.TESTING)

    async def execute(self, state: SDLCState) -> SDLCState:
        state.current_phase = SDLCPhase.TESTING
        self._add_message(state, "Generating unit, integration, and E2E tests...")
        state.test_suites = {
            "unit_tests.py": "# Unit tests",
            "integration_tests.py": "# Integration tests",
            "e2e_tests.py": "# E2E tests",
        }
        return state


class CICDAgent(BaseAgent):
    def __init__(self) -> None:
        super().__init__(AgentType.CICD)

    async def execute(self, state: SDLCState) -> SDLCState:
        state.current_phase = SDLCPhase.DEPLOYMENT
        self._add_message(state, "Creating CI/CD pipelines...")
        state.cicd_config = {
            "Dockerfile": "FROM node:20-alpine\n...",
            "docker-compose.yml": "version: '3.8'\n...",
            ".github/workflows/ci.yml": "name: CI\n...",
        }
        return state


class DeploymentAgent(BaseAgent):
    def __init__(self) -> None:
        super().__init__(AgentType.DEPLOYMENT)

    async def execute(self, state: SDLCState) -> SDLCState:
        self._add_message(state, "Configuring deployment...")
        state.deployment_config = {"vercel.json": "{}", "railway.toml": ""}
        return state


class MonitoringAgent(BaseAgent):
    def __init__(self) -> None:
        super().__init__(AgentType.MONITORING)

    async def execute(self, state: SDLCState) -> SDLCState:
        state.current_phase = SDLCPhase.MONITORING
        self._add_message(state, "Setting up monitoring and observability...")
        return state


class SDLCOrchestrator:
    """Orchestrates the full SDLC pipeline using multiple AI agents."""

    def __init__(self) -> None:
        self.agents: list[BaseAgent] = [
            RequirementsAgent(),
            ArchitectureAgent(),
            DatabaseAgent(),
            FrontendAgent(),
            BackendAgent(),
            TestingAgent(),
            CICDAgent(),
            DeploymentAgent(),
            MonitoringAgent(),
        ]

    async def run_pipeline(self, project_id: str, prompt: str, tech_stack: dict[str, str]) -> SDLCState:
        state = SDLCState(
            project_id=project_id,
            prompt=prompt,
            tech_stack=tech_stack,
        )

        for agent in self.agents:
            try:
                state = await agent.execute(state)
            except Exception as e:
                state.errors.append(f"{agent.agent_type.value}: {e!s}")

        return state
